services:
  mysql:
    image: mysql:8.0
    container_name: product_mysql_container
    restart: always
    env_file:
      - ./express-api/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  expressapi:
    build: ./express-api
    container_name: express-api-container
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - ./express-api/.env
    volumes:
      - .:/app
  
  nextclient:
    build: ./nextapp
    container_name: client-container
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - expressapi
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextclient
      - expressapi
volumes:
  mysql_data:
